databases:
  - name: restaurant
    databaseName: restaurant_4ney
    user: restaurant_4ney_user

services:
  - type: web
    name: restaurants
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurants
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false